// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI_JLXSO_E84LrK9KCqPcxmsIFH3V8vko',
    appId: '1:70151295171:web:e8b6f4c36a80dbcf299276',
    messagingSenderId: '70151295171',
    projectId: 'fireauth-eb88a',
    authDomain: 'fireauth-eb88a.firebaseapp.com',
    storageBucket: 'fireauth-eb88a.firebasestorage.app',
    measurementId: 'G-QD2RYDZQSW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBaJjEcH4yLmNh0C7r2xiou2QFciEWg88',
    appId: '1:70151295171:android:20e9e6d4e140b8b1299276',
    messagingSenderId: '70151295171',
    projectId: 'fireauth-eb88a',
    storageBucket: 'fireauth-eb88a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7qqcQafB247zK1fLoFWTYiFFWH4lWvpg',
    appId: '1:70151295171:ios:d2c6e2dfd27a72b6299276',
    messagingSenderId: '70151295171',
    projectId: 'fireauth-eb88a',
    storageBucket: 'fireauth-eb88a.firebasestorage.app',
    iosBundleId: 'com.example.registerAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7qqcQafB247zK1fLoFWTYiFFWH4lWvpg',
    appId: '1:70151295171:ios:d2c6e2dfd27a72b6299276',
    messagingSenderId: '70151295171',
    projectId: 'fireauth-eb88a',
    storageBucket: 'fireauth-eb88a.firebasestorage.app',
    iosBundleId: 'com.example.registerAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAI_JLXSO_E84LrK9KCqPcxmsIFH3V8vko',
    appId: '1:70151295171:web:af773722826f28e9299276',
    messagingSenderId: '70151295171',
    projectId: 'fireauth-eb88a',
    authDomain: 'fireauth-eb88a.firebaseapp.com',
    storageBucket: 'fireauth-eb88a.firebasestorage.app',
    measurementId: 'G-53LPJEMGRH',
  );
}
